version: 2

# -------------------------------------------------------------------------------------
# Jobs
# -------------------------------------------------------------------------------------
jobs:
  rununittests:
    docker:
      - image: circleci/python:3.7.4-buster
    resource_class: 2xlarge+
    working_directory: ~/CrypTen
    steps:
      - checkout
      - run:
          name: Sets up the virtualenv
          command: |
            python3 -m venv ~/crypten-test
            . ~/crypten-test/bin/activate
            pip3 install --upgrade pip
            pip3 install numpy
            pip3 install --pre torch -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
            # pip3 install torch==1.2.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
            pip3 install onnx tensorboard future
      - run:
          name: Unit tests
          no_output_timeout: 1h
          command: |
            . ~/crypten-test/bin/activate
            echo 'for i in $(ls test/test_*.py | grep -v test_context.py); do python3 -m unittest $i; (($? != 0)) && exit 1; done; exit 0' > run_tests.sh
            bash ./run_tests.sh
      - run:
          name: Linear svm example
          command: |
            . ~/crypten-test/bin/activate
            PYTHONPATH=. python3 examples/mpc_linear_svm/launcher.py
      - run:
          name: Linear svm example
          command: |
            . ~/crypten-test/bin/activate
            PYTHONPATH=. python3 examples/mpc_linear_svm/launcher.py --lr 0.1 --epochs 2 --skip_plaintext
      - run:
          name: Linear svm example multiprocess
          command: |
            . ~/crypten-test/bin/activate
            PYTHONPATH=. python3 examples/mpc_linear_svm/launcher.py --lr 0.1 --world_size 2 --multiprocess
      - run:
          name: Linear svm example multiprocess
          command: |
            . ~/crypten-test/bin/activate
            PYTHONPATH=. python3 examples/mpc_linear_svm/launcher.py --lr 0.1 --world_size 4 --multiprocess
      - run:
          name: Linear svm example multiprocess
          command: |
            . ~/crypten-test/bin/activate
            PYTHONPATH=. python3 examples/mpc_linear_svm/launcher.py --multiprocess
      - run:
          name: TFE benchmarks example
          command: |
            . ~/crypten-test/bin/activate
            pip3 install --pre torchvision -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
            # pip3 install torchvision
            PYTHONPATH=. python3 examples/tfe_benchmarks/launcher.py --network A --epochs 2
            PYTHONPATH=. python3 examples/tfe_benchmarks/launcher.py --network B --epochs 2
            PYTHONPATH=. python3 examples/tfe_benchmarks/launcher.py --network C --epochs 2
      - run:
          name: TFE benchmarks example
          command: |
            . ~/crypten-test/bin/activate
            PYTHONPATH=. python3 examples/tfe_benchmarks/launcher.py --network A --epochs 1 --multiprocess
            PYTHONPATH=. python3 examples/tfe_benchmarks/launcher.py --network B --epochs 1 --multiprocess
            PYTHONPATH=. python3 examples/tfe_benchmarks/launcher.py --network C --epochs 1 --multiprocess
      - run:
          name: TFE benchmarks example
          command: |
            . ~/crypten-test/bin/activate
            PYTHONPATH=. python3 examples/tfe_benchmarks/launcher.py --network A --epochs 3 --multiprocess --world_size 1 --skip-plaintext
            PYTHONPATH=. python3 examples/tfe_benchmarks/launcher.py --network B --epochs 3 --multiprocess --world_size 1 --skip-plaintext
            PYTHONPATH=. python3 examples/tfe_benchmarks/launcher.py --network C --epochs 3 --multiprocess --world_size 1 --skip-plaintext
      - run:
          name: TFE benchmarks example
          command: |
            . ~/crypten-test/bin/activate
            PYTHONPATH=. python3 examples/tfe_benchmarks/launcher.py --network A --multiprocess --evaluate --resume examples/tfe_benchmarks/models/tfe_network_a.pth.tar
            # These consistently break and need to be debugged
            # PYTHONPATH=. python3 examples/tfe_benchmarks/launcher.py --network B --multiprocess --evaluate --resume examples/tfe_benchmarks/models/tfe_network_b.pth.tar
            # PYTHONPATH=. python3 examples/tfe_benchmarks/launcher.py --network C --multiprocess --evaluate --resume examples/tfe_benchmarks/models/tfe_network_c.pth.tar
  runnightlytests:
    docker:
      - image: circleci/python:3.7.4-buster
    resource_class: 2xlarge+
    working_directory: ~/CrypTen
    steps:
      - checkout
      - run:
          name: Sets up the virtualenv
          command: |
            python3 -m venv ~/crypten-test
            . ~/crypten-test/bin/activate
            pip3 install --upgrade pip
            pip3 install numpy
            pip3 install --pre torch -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
            pip3 install onnx tensorboard future torchvision
      - run:
          name: CIFAR example
          command: |
            . ~/crypten-test/bin/activate
            PYTHONPATH=. python3 examples/mpc_cifar/launcher.py
      - run:
          name: CIFAR example
          command: |
            . ~/crypten-test/bin/activate
            PYTHONPATH=. python3 examples/mpc_cifar/launcher.py --multiprocess
      - run:
          name: CIFAR example
          command: |
            . ~/crypten-test/bin/activate
            PYTHONPATH=. python3 examples/mpc_cifar/launcher.py --epochs 2 --batch-size 8 --multiprocess --lr .01
      - run:
          name: CIFAR example
          command: |
            . ~/crypten-test/bin/activate
            PYTHONPATH=. python3 examples/mpc_cifar/launcher.py --epochs 2 --skip-plaintext --world_size 1
            PYTHONPATH=. python3 examples/mpc_cifar/launcher.py --epochs 2 --skip-plaintext --world_size 4
      - run:
          name: CIFAR example
          command: |
            . ~/crypten-test/bin/activate
            PYTHONPATH=. python3 examples/mpc_cifar/launcher.py --epochs 2 --batch-size 16 --multiprocess --evaluate

# -------------------------------------------------------------------------------------
# Workflows
# -------------------------------------------------------------------------------------
workflows:
  version: 2
  commit:
    jobs:
      - rununittests
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - runnightlytests

